SDYH:
  Assets:
    Model: null
    Rig: null
    Surface: null
  Production:
    Edit: null
  Shots:
    Animation: null
    Comp: null
    FX:
      CFX: null
      EFX: null
    Layout: null
    Lighting: null
